name: social_app_firebase
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# locale
  intl:
# equal objects
  equatable:
# state management
  flutter_bloc:
# functional programing
  dartz:
#  check internet
  internet_connection_checker:
# cache storage
  cached_network_image:
  shared_preferences:
# dependency injection
  get_it:
# UI
  carousel_slider:
  fluttertoast:
  image_picker:
# firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
# Random ID
  uuid:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/img/
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icon/icons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
