// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSrHuHjZlgatii1_EmulHJsI4enJ1Xsk',
    appId: '1:371676356630:web:d3063663f23834472e1537',
    messagingSenderId: '371676356630',
    projectId: 'social-app-2-9c11e',
    authDomain: 'social-app-2-9c11e.firebaseapp.com',
    storageBucket: 'social-app-2-9c11e.appspot.com',
    measurementId: 'G-CMHZ1PWD4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQr3TvRNxf8Rh6KCzdVY2c0SHRc1K10c',
    appId: '1:371676356630:android:10c5aff3e70966b22e1537',
    messagingSenderId: '371676356630',
    projectId: 'social-app-2-9c11e',
    storageBucket: 'social-app-2-9c11e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALNSgtiivro-dW4Xh_iLxVYHwhhrmQ1pU',
    appId: '1:371676356630:ios:b6f0b681baaa80c42e1537',
    messagingSenderId: '371676356630',
    projectId: 'social-app-2-9c11e',
    storageBucket: 'social-app-2-9c11e.appspot.com',
    iosClientId: '371676356630-t69kr3j440bqak0odbot54fbpsk97sdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALNSgtiivro-dW4Xh_iLxVYHwhhrmQ1pU',
    appId: '1:371676356630:ios:b6f0b681baaa80c42e1537',
    messagingSenderId: '371676356630',
    projectId: 'social-app-2-9c11e',
    storageBucket: 'social-app-2-9c11e.appspot.com',
    iosClientId: '371676356630-t69kr3j440bqak0odbot54fbpsk97sdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAppFirebase',
  );
}
